pipeline:
  name: testcrot
  identifier: testcrot
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: git-roto
        repoName: harnesscd-example-apps
        build: <+input>
  stages:
    - stage:
        name: rotobuild
        identifier: rotobuild
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: hostname
                    environmentVariables: []
                    outputVariables: []
                    executionTarget:
                      connectorRef: satsatuempat
                      host: 192.168.1.114
                  timeout: 10m
              - step:
                  type: Container
                  name: Container_1
                  identifier: Container_1
                  spec:
                    connectorRef: rotodocker
                    image: rotosetianto/node-harness:v1
                    command: curl -Ls https://bit.ly/harness-cd-linux | bash -
                    shell: Bash
                    infrastructure:
                      type: KubernetesDirect
                      spec:
                        connectorRef: test
                        namespace: default
                        resources:
                          limits:
                            cpu: "4"
                            memory: 5Gi
                        annotations: {}
                        labels: {}
                        containerSecurityContext:
                          capabilities:
                            drop: []
                            add: []
                        nodeSelector: {}
                    outputVariables: []
                    envVariables: {}
                  timeout: 2m
        tags: {}
